os: osx
osx_image: xcode9.3
env:
  - COLUMNS=240
install:
  - brew update
  - brew unlink python
  - brew install advancecomp
  - brew install gdk-pixbuf --without-modules --with-included-loaders="png,jpeg"
  - brew install harfbuzz --without-graphite2
  - brew install vips --with-webp --with-jpeg-turbo --without-fftw --without-poppler
  - brew uninstall vips
  - brew install openexr openslide cfitsio libjpeg-turbo
  - brew install autoconf  gtk-doc swig
  - brew info gdk-pixbuf
  - brew info harfbuzz
  - brew info vips
script:
  - ./pdfium-build.sh
  - ./pdfium-package.sh
  - ./libvips-build.sh
  - ./libvips-package-sharp-tar.sh
addons:
  artifacts:
    s3_region: eu-west-1
